<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.Master" CodeBehind="CodePayments.aspx.cs" Inherits="LanguageCoursesWebApp.CodePayments" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindPayment" runat="server" Text="Label">Платёж</asp:Label><asp:TextBox ID="TextBoxFindPayment" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindPayment" runat="server" Text="Найти" OnClick="ButtonFindPayment_Click" />
    <br />        
        <asp:GridView ID="GridViewPayment" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewPayment_RowCancelingEdit" 
            OnRowDeleting="GridViewPayment_RowDeleting" 
            OnRowEditing="GridViewPayment_RowEditing" 
            OnRowUpdating="GridViewPayment_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewPayment_PageIndexChanging"
            Caption="Платежи" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="PaymentId" HeaderText="Код" SortExpression="PaymentId" />
                <asp:BoundField DataField="NameOfCourses" HeaderText="Наименование курса" SortExpression="NameOfCourses" />
                <asp:BoundField DataField="Date" HeaderText="Дата" SortExpression="Date" />
                <asp:BoundField DataField="Sum" HeaderText="Размер платежа" SortExpression="Sum" />
                <asp:TemplateField HeaderText="Слушатель" SortExpression="ListenerId">
                <EditItemTemplate>
                    <asp:DropDownList ID="ListenerDropDownList" runat="server" DataSourceID="SqlDataSourceListener" DataTextField="nameOfListener" DataValueField="listenerId" SelectedValue='<%# Bind("listenerId") %>'>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                 <asp:Label ID="ListenerId" runat="server"  Text='<%# Eval("Listener.NameOfListener") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
                <asp:TemplateField HeaderText="Дата последнего платежа" SortExpression="LastPaymentDate">
                    <EditItemTemplate>
                        <asp:Calendar ID="LastPaymentDateCalendar" runat="server" SelectedDate='<%# Bind("LastPaymentDate") %>'></asp:Calendar>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="LastPaymentDate" runat="server" Text='<%# Eval("LastPaymentDate") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Курсы" SortExpression="CourseId">
                <EditItemTemplate>
                    <asp:DropDownList ID="CourseDropDownList" runat="server" DataSourceID="SqlDataSourceCourse" DataTextField="nameOfcourse" DataValueField="courseId" SelectedValue='<%# Bind("courseId") %>'>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                 <asp:Label ID="CourseId" runat="server"  Text='<%# Eval("Course.NameOfCourse") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить:</strong>
            <br />
            <asp:label runat="server">Наименование курса:</asp:label><asp:TextBox ID="TextBoxNameOfCourse" runat="server"></asp:TextBox>
            <br />
           <asp:label runat="server">Дата:</asp:label><asp:Calendar ID="TextBoxDate" runat="server"></asp:Calendar>
            <br />
            <asp:label runat="server">Сумма платежа:</asp:label><asp:TextBox ID="TextBoxSum" runat="server"></asp:TextBox>
            <br />
            Учитель
           <asp:DropDownList ID="ListenerDropDownList" DataSourceID="SqlDataSourceListener" DataValueField="listenerId" DataTextField="nameOfListener" runat="server"></asp:DropDownList>
            <br />
            <asp:label runat="server">Дата последнего платежа:</asp:label><asp:Calendar ID="TextBoxLastPaymentDate" runat="server"></asp:Calendar>
            <br /> 
            Учитель
           <asp:DropDownList ID="CourseDropDownList" DataSourceID="SqlDataSourceCourse" DataValueField="courseId" DataTextField="nameOfCourse" runat="server"></asp:DropDownList>
        </td>
        <td>
            <asp:Button ID="ButtonAddPayment" runat="server" Text="Добавить" OnClick="ButtonAddPayment_Click" />

        </td>
</tr>
</table>
    <asp:SqlDataSource ID="SqlDataSourceListener" runat="server" 
        ConnectionString="<%$ ConnectionStrings:LanguageConnectionString %>" 
        SelectCommand="SELECT [listenerId], [nameOfListener] FROM [Listeners]">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceCourse" runat="server" 
        ConnectionString="<%$ ConnectionStrings:LanguageConnectionString %>" 
        SelectCommand="SELECT [courseId], [nameOfCourse] FROM [Courses]">
    </asp:SqlDataSource>
    </asp:Content>

